<?php

use App\Models\Client;
use App\Models\RecurringInvoiceProfile;
use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;

uses(RefreshDatabase::class);

function validRecurringPayload(string $clientId): array
{
    return [
        'client_id' => $clientId,
        'name' => 'Monthly retainers',
        'frequency' => 'monthly',
        'start_date' => now()->toDateString(),
        'next_due_date' => now()->toDateString(),
        'day_of_month' => 15,
        'line_items' => [
            [
                'description' => 'Monthly retainer',
                'quantity' => 1,
                'unit_price' => 1200,
                'vat_rate' => 20,
            ],
        ],
        'notes' => 'Autogenerated profile',
        'payment_terms_days' => 30,
        'tax_rate' => 20,
        'discount_percent' => 0,
        'auto_send' => true,
        'currency' => 'EUR',
    ];
}

test('user can create read update and delete recurring invoice profile', function () {
    $user = User::factory()->create();
    $client = Client::factory()->create(['user_id' => $user->id]);

    $create = $this->actingAs($user, 'sanctum')
        ->postJson('/api/v1/recurring-invoices', validRecurringPayload($client->id));

    $create->assertStatus(201)
        ->assertJsonPath('data.client_id', $client->id)
        ->assertJsonPath('data.frequency', 'monthly')
        ->assertJsonPath('data.status', 'active');

    $profileId = (string) $create->json('data.id');

    $show = $this->actingAs($user, 'sanctum')
        ->getJson('/api/v1/recurring-invoices/'.$profileId);

    $show->assertStatus(200)
        ->assertJsonPath('data.id', $profileId);

    $update = $this->actingAs($user, 'sanctum')
        ->putJson('/api/v1/recurring-invoices/'.$profileId, [
            ...validRecurringPayload($client->id),
            'name' => 'Updated profile name',
            'frequency' => 'quarterly',
        ]);

    $update->assertStatus(200)
        ->assertJsonPath('data.name', 'Updated profile name')
        ->assertJsonPath('data.frequency', 'quarterly');

    $this->actingAs($user, 'sanctum')
        ->postJson('/api/v1/recurring-invoices/'.$profileId.'/pause')
        ->assertStatus(200)
        ->assertJsonPath('data.status', 'paused');

    $this->actingAs($user, 'sanctum')
        ->postJson('/api/v1/recurring-invoices/'.$profileId.'/resume')
        ->assertStatus(200)
        ->assertJsonPath('data.status', 'active');

    $this->actingAs($user, 'sanctum')
        ->postJson('/api/v1/recurring-invoices/'.$profileId.'/cancel')
        ->assertStatus(200)
        ->assertJsonPath('data.status', 'cancelled');

    $this->actingAs($user, 'sanctum')
        ->deleteJson('/api/v1/recurring-invoices/'.$profileId)
        ->assertStatus(200);

    $this->assertDatabaseMissing('recurring_invoice_profiles', ['id' => $profileId]);
});

test('recurring profile validation rejects invalid frequency and day of month', function () {
    $user = User::factory()->create();
    $client = Client::factory()->create(['user_id' => $user->id]);

    $response = $this->actingAs($user, 'sanctum')
        ->postJson('/api/v1/recurring-invoices', [
            ...validRecurringPayload($client->id),
            'frequency' => 'daily',
            'day_of_month' => 42,
        ]);

    $response->assertStatus(422)
        ->assertJsonValidationErrors(['frequency', 'day_of_month']);
});

test('user cannot access another user recurring profile', function () {
    $owner = User::factory()->create();
    $other = User::factory()->create();

    $profile = RecurringInvoiceProfile::factory()->create([
        'user_id' => $owner->id,
    ]);

    $this->actingAs($other, 'sanctum')
        ->getJson('/api/v1/recurring-invoices/'.$profile->id)
        ->assertStatus(403);
});

